image:
  repository: "gcr.io/workable-k8s/megatron"
  tag: null
  pullPolicy: IfNotPresent

scale:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

resources:
  limits:
    cpu: 5
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 1Gi
